package at.backend.MarketingCompany.marketing.metric.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class CampaignMetricId extends NumericId {
	public CampaignMetricId(Long value) {
		super(value);
	}

	public static CampaignMetricId of(String id) {
		return NumericId.fromString(id, CampaignMetricId::new);
	}

	// Id Will be generated by the database
	public static CampaignMetricId generate() {
		return new CampaignMetricId(null);
	}

	public String asString() {
		return this.getValue().toString();
	}
}
