package at.backend.MarketingCompany.crm.opportunity.core.domain.entity.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class OpportunityId extends NumericId {
  public OpportunityId(Long value) {
    super(value);
  }

  public static OpportunityId of(String id) {
    return NumericId.fromString(id, OpportunityId::new);
  }

  // Id Will be generated by the database
  public static OpportunityId generate() {
    return new OpportunityId(0L);
  }
}
