package at.backend.MarketingCompany.crm.servicePackage.core.domain.entity.valueobjects;

import at.backend.MarketingCompany.shared.domain.NumericId;
import at.backend.MarketingCompany.shared.domain.exceptions.MissingFieldException;

import java.util.UUID;


public class ServicePackageId extends NumericId {
    public ServicePackageId(Long value) {
        super(value);
    }

    public static ServicePackageId of(String id) {
        return NumericId.fromString(id, ServicePackageId::new);
    }

    // Id Will be generated by the database
    public static ServicePackageId generate() {
        return new ServicePackageId(null);
    }
}
