package at.backend.MarketingCompany.marketing.attribution.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class CampaignAttributionId extends NumericId {
	public CampaignAttributionId(Long value) {
		super(value);
	}

	public static CampaignAttributionId of(String id) {
		return NumericId.fromString(id, CampaignAttributionId::new);
	}

	// Id Will be generated by the database
	public static CampaignAttributionId generate() {
		return new CampaignAttributionId(null);
	}

	public String asString() {
		return this.getValue().toString();
	}
}
