package at.backend.MarketingCompany.marketing.ab_test.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class AbTestId extends NumericId {
	public AbTestId(Long value) {
		super(value);
	}

	public static AbTestId of(String id) {
		return NumericId.fromString(id, AbTestId::new);
	}

	// Id Will be generated by the database
	public static AbTestId generate() {
		return new AbTestId(0L);
	}

	public String asString() {
		return this.getValue().toString();
	}
}
