package at.backend.MarketingCompany.marketing.activity.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class CampaignActivityId extends NumericId {
	public CampaignActivityId(Long value) {
		super(value);
	}

	public static CampaignActivityId of(String id) {
		return NumericId.fromString(id, CampaignActivityId::new);
	}

	// Id Will be generated by the database
	public static CampaignActivityId generate() {
		return new CampaignActivityId(null);
	}

	public String asString() {
		return this.getValue().toString();
	}


}


