package at.backend.MarketingCompany.marketing.channel.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class MarketingChannelId extends NumericId {
	public MarketingChannelId(Long value) {
		super(value);
	}

	public static MarketingChannelId of(String id) {
		return NumericId.fromString(id, MarketingChannelId::new);
	}

	// Id Will be generated by the database
	public static MarketingChannelId generate() {
		return new MarketingChannelId(0L);
	}

	public String asString() {
		return this.getValue().toString();
	}
}
