package at.backend.MarketingCompany.customer.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;


public class CustomerCompanyId extends NumericId {
    public CustomerCompanyId(Long value) {
        super(value);
    }

    public static CustomerCompanyId of(String id) {
        return NumericId.fromString(id, CustomerCompanyId::new);
    }

    // Id Will be generated by the database
    public static CustomerCompanyId generate() {
        return new CustomerCompanyId(null);
    }
}
