package at.backend.MarketingCompany.marketing.interaction.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class CampaignInteractionId extends NumericId {
  public CampaignInteractionId(Long value) {
    super(value);
  }

  public static CampaignInteractionId of(String id) {
    return NumericId.fromString(id, CampaignInteractionId::new);
  }

  // Id Will be generated by the database
  public static CampaignInteractionId generate() {
    return new CampaignInteractionId(0L);
  }

}
