package at.backend.MarketingCompany.marketing.campaign.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class MarketingCampaignId extends NumericId {
	public MarketingCampaignId(Long value) {
		super(value);
	}

	public static MarketingCampaignId of(String id) {
		return NumericId.fromString(id, MarketingCampaignId::new);
	}

	// Id Will be generated by the database
	public static MarketingCampaignId generate() {
		return new MarketingCampaignId(0L);
	}

	public String asString() {
		return this.getValue().toString();
	}
}
