package at.backend.MarketingCompany.shared.domain.marketingCampaing;

public enum ActivityType {
    EMAIL_BLAST,
    NEWSLETTER,
    SOCIAL_POST,
    SOCIAL_AD,
    BLOG_POST,
    WHITE_PAPER,
    CASE_STUDY,
    EBOOK,
    WEBINAR,
    PHYSICAL_EVENT,
    VIRTUAL_EVENT,
    PRESS_RELEASE,
    DIRECT_MAIL,
    PPC_CAMPAIGN,
    SEO_UPDATE,
    LANDING_PAGE,
    VIDEO_PRODUCTION,
    PODCAST,
    TRADESHOW,
    SMS_CAMPAIGN,
    INFLUENCER_OUTREACH,
    PRINT_AD,
    TV_AD,
    RADIO_AD,
    PR_CAMPAIGN,
    CONTENT_SYNDICATION,
    AFFILIATE_CAMPAIGN,
    CUSTOM
}

