package at.backend.MarketingCompany.marketing.asset.core.domain.valueobject;

import at.backend.MarketingCompany.shared.domain.NumericId;

public class MarketingAssetId extends NumericId {
	public MarketingAssetId(Long value) {
		super(value);
	}

	public static MarketingAssetId of(String id) {
		return NumericId.fromString(id, MarketingAssetId::new);
	}

	// Id Will be generated by the database
	public static MarketingAssetId generate() {
		return new MarketingAssetId(null);
	}

	public String asString() {
		return this.getValue().toString();
	}
}
